[build]
functions = "netlify/functions"
command = "netlify-lambda install && mkdir ./public"
[template.environment]
DISCORD_API_TOKEN = ""
TOKEN_ID = ""
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200