[functions]
  node_bundler = "zisi"
  included_files = ["dist/**"]
  external_node_modules = ["ffmpeg-static"]

[build]
  publish = "dist"
  functionsSource = "netlify/functions"
  functions = "dist/functions"
  
[dev]
  functionsSource = "netlify/functions"
  functions = "dist/functions"
